# Perception Layer Configuration
# Controls blob labeling, feature extraction, and symmetry detection

# Blob labeling settings
blob_labeling:
  use_gpu: false
  fallback_to_cpu: true
  max_labeling_time: 0.01  # advisory only
  connectivity: 4  # 4-connected or 8-connected components
  
# Feature extraction settings
features:
  # Orbit signature computation (D₄ symmetry fingerprinting)
  orbit_signature:
    enabled: true
    dimension: 8  # 8-dimensional orbit signatures
    
  # Spectral features (Laplacian eigenvalues)
  spectral:
    enabled: true
    dimension: 3
    eigenvalue_tolerance: 1e-3
    max_eigenvalue_time: 0.01
    
  # Persistent homology features
  persistence:
    enabled: true
    dimension: 32
    max_homology_time: 0.05
    cubical_complex: true
    
  # Zernike moment features
  zernike:
    enabled: true
    dimension: 7
    max_order: 4
    invariance_tolerance: 1e-4
    
  # Combined feature vector
  total_dimension: 50
  
# Symmetry detection settings
symmetry:
  use_bitboards: true
  max_detection_time: 0.00005
  early_exit: true
  check_rotations: true  # Check 4 rotations
  check_reflections: true  # Check 4 reflections
  
# Performance monitoring
monitoring:
  track_timing: true  # Track computation times
  warn_slow_operations: true  # Warn on slow operations
  log_feature_failures: true  # Log feature computation failures