name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONHASHSEED: "42"
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pytest flake8 black mypy

      - name: Lint (flake8)
        run: |
          flake8 src tests scripts || true

      - name: Format check (black)
        run: |
          black --check src tests scripts || true

      - name: Type check (mypy)
        run: |
          mypy src || true

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q

      - name: Smoke ARC-AGI-2 runner (optional)
        env:
          PYTHONPATH: src
        run: |
          if [ -d "data/smoke" ]; then python scripts/arc_agi2_runner.py --data-dir data/smoke --output outputs/smoke_results.json --max-tasks 5; fi

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/

